# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\pyqt_diplom\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 441)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftSideW = QtWidgets.QWidget(self.centralwidget)
        self.leftSideW.setObjectName("leftSideW")
        self.formLayout = QtWidgets.QFormLayout(self.leftSideW)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.leftSideW)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.materialCB_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.materialCB_4.setMinimumSize(QtCore.QSize(100, 0))
        self.materialCB_4.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.materialCB_4.setCurrentText("")
        self.materialCB_4.setObjectName("materialCB_4")
        self.verticalLayout_2.addWidget(self.materialCB_4)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.groupBox_3)
        self.pushButton = QtWidgets.QPushButton(self.leftSideW)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.leftSideW)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.materialCB = QtWidgets.QComboBox(self.groupBox_2)
        self.materialCB.setMinimumSize(QtCore.QSize(100, 0))
        self.materialCB.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.materialCB.setObjectName("materialCB")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.materialCB.addItem("")
        self.horizontalLayout_2.addWidget(self.materialCB)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.leftSideW)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.materialCB_2 = QtWidgets.QComboBox(self.groupBox)
        self.materialCB_2.setMinimumSize(QtCore.QSize(60, 0))
        self.materialCB_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.materialCB_2.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.materialCB_2.setCurrentText("")
        self.materialCB_2.setObjectName("materialCB_2")
        self.gridLayout_2.addWidget(self.materialCB_2, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 1, 1, 1)
        self.materialCB_3 = QtWidgets.QComboBox(self.groupBox)
        self.materialCB_3.setMinimumSize(QtCore.QSize(60, 0))
        self.materialCB_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.materialCB_3.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.materialCB_3.setCurrentText("")
        self.materialCB_3.setObjectName("materialCB_3")
        self.gridLayout_2.addWidget(self.materialCB_3, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.groupBox)
        self.horizontalLayout.addWidget(self.leftSideW)
        self.rightSideW = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightSideW.sizePolicy().hasHeightForWidth())
        self.rightSideW.setSizePolicy(sizePolicy)
        self.rightSideW.setMinimumSize(QtCore.QSize(380, 0))
        self.rightSideW.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightSideW.setObjectName("rightSideW")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rightSideW)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addWidget(self.rightSideW)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openSettingsAction = QtWidgets.QAction(MainWindow)
        self.openSettingsAction.setObjectName("openSettingsAction")
        self.saveSettingsAction = QtWidgets.QAction(MainWindow)
        self.saveSettingsAction.setObjectName("saveSettingsAction")
        self.saveAsSettingsAction = QtWidgets.QAction(MainWindow)
        self.saveAsSettingsAction.setObjectName("saveAsSettingsAction")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Вид отверстия"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Обрабатываемые материалы"))
        self.materialCB.setCurrentText(_translate("MainWindow", "Углеродистые конструкционные "))
        self.materialCB.setItemText(0, _translate("MainWindow", "Углеродистые конструкционные "))
        self.materialCB.setItemText(1, _translate("MainWindow", "Инструментальные "))
        self.materialCB.setItemText(2, _translate("MainWindow", "Хромистые, хромоникелевые, марганцовистые "))
        self.materialCB.setItemText(3, _translate("MainWindow", "Теплоустойчивые ферритного класса"))
        self.materialCB.setItemText(4, _translate("MainWindow", "Конструкционные "))
        self.materialCB.setItemText(5, _translate("MainWindow", "Коррозионно-стойкие"))
        self.materialCB.setItemText(6, _translate("MainWindow", "Жаростойкие "))
        self.materialCB.setItemText(7, _translate("MainWindow", "Жаропрочные деформируемые"))
        self.materialCB.setItemText(8, _translate("MainWindow", "Жаропрочные литейные"))
        self.materialCB.setItemText(9, _translate("MainWindow", "Высокопрочные "))
        self.materialCB.setItemText(10, _translate("MainWindow", "Титановые"))
        self.materialCB.setItemText(11, _translate("MainWindow", "Цветные типа алюминиевых, магниевых, медных"))
        self.materialCB.setItemText(12, _translate("MainWindow", "Чугуны всех марок"))
        self.groupBox.setTitle(_translate("MainWindow", "Параметры резьбы"))
        self.label_2.setText(_translate("MainWindow", "Диаметр"))
        self.label_3.setText(_translate("MainWindow", "Шаг"))
        self.label_4.setText(_translate("MainWindow", "Точность"))
        self.label_5.setText(_translate("MainWindow", "Длина"))
        self.openSettingsAction.setText(_translate("MainWindow", "Открыть файл"))
        self.saveSettingsAction.setText(_translate("MainWindow", "Сохранить"))
        self.saveAsSettingsAction.setText(_translate("MainWindow", "Сохранить как"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

